[package]
name = "ex0901"
version = "0.1.0"
authors = ["Thomas SJ Kang <ujuc@ujuc.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
